### PR TITLE
Add set up script for local development

### PR DESCRIPTION
**Pull request by maxbeizer**
## Description / What does this PR do?
It allows for easier development by adding a script to set up the dev db.

## Remaining Todos
* [x] Update README with this step
* [x] Add a way to prime local db with development data??

### CODE REVIEW

**Comment by maxbeizer** [comment]
@egdelwonk WDYT?

**Comment by egdelwonk** [comment]
Looks good! Do you mind dropping `setup.js` into /scripts? Also it might be useful to write some seeds too, but we can add that into another PR.  https://knexjs.org/#Seeds-CLI

**Comment by maxbeizer** [comment]
I'm looking into the seeds stuff. It looks like this doesn't quote work as expected so I'm going to keep hacking away at it

**Comment by maxbeizer** [comment]
@egdelwonk updated. LMK what you think 😸

**Comment by egdelwonk** [comment]
Looks good! Thanks 🤩

**Pull request merged**
